DROP TABLE MEMBER;

CREATE TABLE MEMBER(
ID INT AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
PASSWORD VARCHAR(200) NOT NULL,
PHONE VARCHAR(16) NOT NULL,
NAME VARCHAR(40) NOT NULL,
BIRTH DATE NOT NULL,
ADDRESS VARCHAR(150) NOT NULL,
GENDER ENUM('M', 'F'),
FOREIGNER ENUM('K', 'F')
);

COMMIT;

 FOREIGN KEY (main_table_id) REFERENCES main_table(id) ON DELETE CASCADE